/*
 * Avatar in index & Subforums for Forumotion Boards.
 * ©Copyright by Toxigeek All Rights Reserved.
 * By giObanii - Toxigeek.com
*/
 
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('8 z(){9 11=\'©12 13 14. ©15.16. 17 18 19\';u(c===\'1a\'||c===\'1b\'){$(\'.m q .A\').r(\'.F\').B(\'C\');$(\'.m q .n[G="H%"], .m q .I[G="H%"]\').d(8(s){$(6).r(\'.n[J="K"], .I[J="K"]\').e(\'<4 f="2-7\'+s+\'" g="2-3 2-7"><4>\');9 b=$(\'.m q .A\').L().o(\'.C\').o(\'v\').o(\'t\').o(\'a\').M(\'h\');$(\'#2-7\'+s).j(b+\' .m .n.N[O="w"]:5(0) k:5(0)\')});$(\'.m q .A.F\').d(8(i){$(6).e(\'<4 f="2-3\'+i+\'" g="2-3"><4>\');9 a=6.l(\'v\')[0].l(\'v\')[0].l(\'t\')[0].x.h;$(\'#2-3\'+i).j(a+\' .m .n.N[O="w"]:5(0) k:5(0)\')})}D u(c===\'1c\'||c===\'1d\'){$(\'.P.1e .Q .1f\').d(8(s){$(6).e(\'<4 f="2-7\'+s+\'" g="2-3 2-7"><4>\');9 b=6.1g(\'v-1h\')[0].l(\'t\')[0].x.h;$(\'#2-7\'+s).j(b+\' #R-S-T .p:5(0) k:5(0)\')});$(\'.P.1i .Q .1j\').d(8(i){$(6).e(\'<4 f="2-3\'+i+\'" g="2-3"><4>\');9 a=6.l(\'t\')[0].x.h;$(\'#2-3\'+i).j(a+\' #R-S-T .p:5(0) k:5(0)\')})}D u(c===\'1k\'||c===\'1l\'||c===\'1m\'){$(\'.y.3-E .n\').r(\'.U\').B(\'V\');$(\'.y\').r(\'.3-E\').B(\'W\');$(\'.y.3-E .n.V\').d(8(i){$(6).e(\'<4 f="2-3\'+i+\'" g="2-3"><4>\');9 a=6.l(\'t\')[0].x.h;$(\'#2-3\'+i).j(a+\' .p:5(1) k:5(0)\')});$(\'.y.W .n\').d(8(s){$(6).r(\'.U, .1n\').e(\'<4 f="2-7\'+s+\'" g="2-3 2-7"><4>\');9 b=$(6).L().o(\'.C\').o(\'a\').M(\'h\');$(\'#2-7\'+s).j(b+\' .p:5(1) k:5(0)\')})}D u(c===\'1o\'||c===\'1p\'){$(\'.X .1q\').d(8(s){$(6).e(\'<4 f="2-7\'+s+\'" g="2-3 2-7"><4>\');9 b=6.l(\'a\')[1].h;$(\'#2-7\'+s).j(b+\' .p .Y-Z.10.w:5(0) k:5(0)\')});$(\'.X .1r\').d(8(i){$(6).e(\'<4 f="2-3\'+i+\'" g="2-3"><4>\');9 a=6.l(\'a\')[1].h;$(\'#2-3\'+i).j(a+\' .p .Y-Z.10.w:5(0) k:5(0)\')})}};1s?z():$(8(){z()});',62,91,'||avatar|index|div|eq|this|subforo|function|var|||versionForum|each|prepend|id|class|href||load|img|getElementsByTagName|forumline|row1|children|module|tr|not||strong|if|span|center|firstChild|ipbtable|tg_avatar_index|row3|addClass|author|else|box|over|width|100|row2|height|50|parent|attr|gensmall|align|topiclist|row|profile|advanced|right|centered|laspost|subforum|statused|main|content|clearfix|Copyrights|Copyright|by|giObanii|toxigeek|com|All|Rights|Reserved|phpbb2|PHPBB2|phpbb3|PHPBB3|topics|dterm|getElementsByClassName|tab|forums|lastpost|invision|Invision|INVISION|lastaction|punbb|PUNBB|tdtopics|tcr|READY_AVATAR'.split('|'),0,{}))

$(function () {$('body').after('<div style="background: none repeat scroll 0 0 #FEB6B6;border: 1px solid #FF0000;font-size: 15px;padding: 10px;position: fixed;text-align: center;top: 1px;width: 100%;">Estas utilizando una versi&oacute;n obsoleta del script <strong>AVATAR EN EL INDEX</strong> de <strong>Toxigeek.com</strong> el cual sera removido en un plazo de 24hrs., es necesario actualizar al codig&oacute; m&aacute;s reciente. M&aacute;s informaci&oacute;n <a href="http://toxigeek.com/foroactivo/mostrar-avatar-en-el-index-subforos-del-autor-de-cada-tema.html">AQUI</a></div>');});
