function tg_float_social() {
$('head').append('<style type="text/css">#f-Facebook{position:fixed;top:100px;right:-250px;float:right;width:288px;display:block;padding:0;z-index:1002;-moz-transition:all 1s;-webkit-transition:all 1s;-o-transition:all 1s}.f-Facebook{background: #3c5a98; height:325px; margin-left:38px;padding: 8px 5px 0pt 50px;border-radius: 0px 0px 0px 10px;}#f-Twitter{position:fixed;top:240px;right:-250px;float:right;width:288px;display:block;padding:0;z-index:1003;border-radius:10px;-moz-transition:all 1s;-webkit-transition:all 1s;-o-transition:all 1s}.f-Twitter{background: #00a0e8; height:325px; margin-left:38px;padding: 8px 5px 0pt 50px;border-radius: 0px 0px 0px 10px;}#f-Google{position:fixed;top:380px;right:-250px;float:right;width:288px;display:block;padding:0;z-index:1004;border-radius:10px;-moz-transition:all 1s;-webkit-transition:all 1s;-o-transition:all 1s}.f-Google{background: #9A9FA8; height:325px; margin-left:38px;padding: 8px 5px 0pt 50px;border-radius: 0px 0px 0px 10px;}#f-Facebook:hover,#f-Google:hover,#f-Twitter:hover{right:0;-moz-transition:all 1s;-webkit-transition:all 1s;-o-transition:all 1s}div.likeboxwrap{margin-top:-5px;margin-left:-45px;width:238px;height:325px;background-color:#fff;overflow:hidden;border-radius:10px}</style>');
if (FS_FACEBOOK === true) {
$('body').append('<div id="f-Facebook"><img src="http://goo.gl/zJ4Az" style="float:left;"/><div class="f-Facebook"><span><div class="likeboxwrap"><iframe allowtransparency="true" frameborder="0" scrolling="no" src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2F'+ NAME_PAGE +'&width=240&colorscheme=light&connections=15&stream=false&header=false&height=350" style="border:none; overflow:hidden; width:240px; height:325px;"/></iframe></div></span></div></div>');
};
if (FS_TWITTER === true) {
$.getScript('http://goo.gl/3Fp1h');
$('body').append('<div id="f-Twitter"><img src="http://goo.gl/y4ft9" style="float:left;"/><div class="f-Twitter"><span><div class="likeboxwrap"><div id="twitterfollowbox" class="follow-box-container"></div></div></span></div></div>');
$('head').append('<style type="text/css">.follow_box_widget{overflow:hidden;padding-left:5px;padding-right:5px;padding-top:5px;background-color:#fff transparent;position:relative;margin:auto}.follow_box{font-size:11px;font-family:"lucida grande",tahoma,verdana,arial,sans-serif;color:#333;line-height:1.28;text-align:left;direction:ltr}.follow_box .follow_top{padding:5px 10px 0 5px;margin-bottom:8px;min-width:230px;overflow:hidden}.follow_box .profileimage{float:left;width:40px;height:40px;padding:0;margin:0 10px 4px 0}.follow_box img{border:0}.follow_box a{cursor:pointer;color:#3b5998;text-decoration:none}.follow_box a:hover{text-decoration:underline}.follow_action{padding:0 0 0 8px}.follow_box .follow_action .name{line-height:15px;font-size:14px;font-weight:bold}.follow_box .follow_button{margin:5px 0 0}.follow_box .total{min-width:230px;overflow:hidden;display:block}.follow_box .connections{padding:5px 0 4px 0;border-top:solid 1px #d8dfea;border-bottom:1px solid #CCC;min-height:150px}.follow_box .connections .connections_grid{padding-top:5px;overflow:hidden}.follow_box .clearfix{zoom:1}.follow_box .connections .connections_grid .grid_item{float:left;margin:0;margin-right:5px;margin-bottom:8px;overflow:hidden;width:50px}.follow_box .connections .connections_grid .grid_item .name{font-size:9px;color:gray;overflow:hidden;padding-top:2px;text-align:center;white-space:nowrap}.follow_box .connections .connections_grid .grid_item img{width:48px;height:48px}.follow_box .follow_widget_footer{cursor:default;width:100%;min-width:230px;overflow:hidden}.follow_box .footer_border{margin-top:5px}.follow_box .uiImageBlock{line-height:14px}.follow_box .follow_widget_footer .footer_logo{float:left;margin-right:5px}.follow_box .follow_widget_footer .footer_text{cursor:default;color:gray;font-size:9px;float:left}.follow_box .follow_widget_footer .footer_text a.footer_text_link{color:gray}.follow_box .titlecase{text-transform:capitalize}</style>');
};
if (FS_GOOGLEPS === true) {
$('body').append('<div id="f-Google"><img src="http://goo.gl/pk5vk" style="float:left;"/><div class="f-Google"><span><div class="likeboxwrap" style="padding-left:20px; padding-top:15px; height:310px !important;"><div class="g-plus" data-action="followers" data-height="300" data-href="https://plus.google.com/'+ USER_ID +'" data-source="blogger:blog:followers" data-width="240"></div><script type="text/javascript"> (function() { window.___gcfg = {"lang": "es"}; var po = document.createElement("script"); po.type = "text/javascript"; po.async = true; po.src = "https://apis.google.com/js/plusone.js"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(po, s); })();</script></div></span></div></div>');
};
};
READY_FSOCIAL ? tg_float_social() : $(function () {
    tg_float_social();
});